"""
Demo portfolio and data used for the canned demo video.

Import DEMO_PORTFOLIO wherever a realistic example portfolio is needed.
"""

DEMO_PORTFOLIO = {
    "user_id": "demo_user",
    "holdings": [
        # ── Index ETFs (core) ─────────────────────────────────────────────────
        {
            "ticker": "SPY",
            "name": "SPDR S&P 500 ETF",
            "shares": 50,
            "value": 22000,
            "cost_basis": 17500,
            "holding_period_days": 820,
        },
        {
            "ticker": "QQQ",
            "name": "Invesco QQQ Trust",
            "shares": 20,
            "value": 9800,
            "cost_basis": 7200,
            "holding_period_days": 540,
        },
        {
            "ticker": "VOO",
            "name": "Vanguard S&P 500 ETF",
            "shares": 15,
            "value": 7200,
            "cost_basis": 5400,
            "holding_period_days": 1100,
        },
        {
            "ticker": "VTI",
            "name": "Vanguard Total Stock Market ETF",
            "shares": 25,
            "value": 5800,
            "cost_basis": 4500,
            "holding_period_days": 730,
        },
        # ── International / Bond ETFs ─────────────────────────────────────────
        {
            "ticker": "VEA",
            "name": "Vanguard Developed Markets ETF",
            "shares": 60,
            "value": 2900,
            "cost_basis": 3100,
            "holding_period_days": 400,
        },
        {
            "ticker": "BND",
            "name": "Vanguard Total Bond Market ETF",
            "shares": 40,
            "value": 3100,
            "cost_basis": 3300,
            "holding_period_days": 950,
        },
        # ── Individual stocks ─────────────────────────────────────────────────
        {
            "ticker": "AAPL",
            "name": "Apple Inc.",
            "shares": 18,
            "value": 3800,
            "cost_basis": 2600,
            "holding_period_days": 1440,
        },
        {
            "ticker": "MSFT",
            "name": "Microsoft Corp.",
            "shares": 8,
            "value": 3400,
            "cost_basis": 2200,
            "holding_period_days": 1200,
        },
        {
            "ticker": "GOOGL",
            "name": "Alphabet Inc.",
            "shares": 12,
            "value": 2200,
            "cost_basis": 1700,
            "holding_period_days": 600,
        },
        {
            "ticker": "AMZN",
            "name": "Amazon.com Inc.",
            "shares": 10,
            "value": 1900,
            "cost_basis": 1400,
            "holding_period_days": 480,
        },
        {
            "ticker": "TSLA",
            "name": "Tesla Inc.",
            "shares": 15,
            "value": 4200,
            "cost_basis": 5800,
            "holding_period_days": 320,
        },
        {
            "ticker": "META",
            "name": "Meta Platforms Inc.",
            "shares": 7,
            "value": 3700,
            "cost_basis": 2300,
            "holding_period_days": 510,
        },
        {
            "ticker": "NVDA",
            "name": "NVIDIA Corp.",
            "shares": 5,
            "value": 5500,
            "cost_basis": 1800,
            "holding_period_days": 900,
        },
        {
            "ticker": "NFLX",
            "name": "Netflix Inc.",
            "shares": 4,
            "value": 2800,
            "cost_basis": 2200,
            "holding_period_days": 270,
        },
        {
            "ticker": "CRM",
            "name": "Salesforce Inc.",
            "shares": 6,
            "value": 1600,
            "cost_basis": 1700,
            "holding_period_days": 180,
        },
    ],
    "total_value": 80000,
    "cash": 4500,
    "last_updated": "2026-03-12",
    # Simulated monthly snapshots for growth chart (18 months back → today)
    "growth_history": [
        {"month": "Sep 2024", "value": 58000},
        {"month": "Oct 2024", "value": 60500},
        {"month": "Nov 2024", "value": 64000},
        {"month": "Dec 2024", "value": 62500},
        {"month": "Jan 2025", "value": 66000},
        {"month": "Feb 2025", "value": 68500},
        {"month": "Mar 2025", "value": 70000},
        {"month": "Apr 2025", "value": 69000},
        {"month": "May 2025", "value": 72000},
        {"month": "Jun 2025", "value": 74500},
        {"month": "Jul 2025", "value": 73000},
        {"month": "Aug 2025", "value": 75500},
        {"month": "Sep 2025", "value": 76000},
        {"month": "Oct 2025", "value": 77500},
        {"month": "Nov 2025", "value": 78000},
        {"month": "Dec 2025", "value": 76500},
        {"month": "Jan 2026", "value": 79000},
        {"month": "Feb 2026", "value": 80000},
    ],
}
